version: '3'

services:
  db:
    image: postgres:12-alpine
    ports:
    - "4000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: Sharing_DB
    restart: always

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
#    ports:
#      - "5672:5672"
#      - "15672:15672"
    labels:
      NAME: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=vhost
    restart: always

  web:
    build: .
    volumes:
    - .:/file_sharing_service
    command: >
      /bin/bash -c "
        sleep 10
        python3 manage.py db init
        python3 manage.py db upgrade
        python3 manage.py db migrate
        python3 manage.py db upgrade
        python3 app.py"
    ports:
    - "4100:5000"
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq